### ISSUE TITLE
Does OFFLINE count

### ISSUE THREAD

**Issue by totaljerkface216** [luca28pet/TimeRanks#11]
If a player is offline will it still count as time. or does the player have to be on for a certain amount of time.
say a rank up is 20 min
a player plays for 15min and gets off
will those last 5 min count when the player is off / will the player rank up even tho he is offline.
or
is it that  he needs to be online for 20 min to rank
he playes 15 gets off and does not rank up
gets back on plays 5 min and then ranks up.

**Comment by fycarman** [comment]
To answer to your question, the player need to stay 20 minutes online, if he quits after 15 minutes, only 15 minutes are counted, and then when he comes back, he can reach 20 minutes and rankup.
