### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Pub4Game** [luca28pet/TimeRanks#2]
Pub4Game has played 2 minutes on this server
Произошла неизвестная ошибка при выполнении команды
[Server thread/CRITICAL]: Необработанное исключение при выполнении команды 'tr check Pub4Game' в timeranks: Undefined index: minutes
[Server thread/NOTICE]: ArrayOutOfBoundsException: "Undefined index: minutes" (E_NOTICE) in "/TimeRanks-master/src/TimeRanks/Main" at line 92

**Comment by luca28pet** [comment]
Released 1.0.2 that fixes it
