### ISSUE TITLE
Data-Provider  Options

### ISSUE THREAD

**Issue by BobbyTowers** [luca28pet/TimeRanks#6]
I'm switching to the new version but it uses sqlite3. Can you add the option to use the old yml for the data provider? Or does it have it already?

**Comment by luca28pet** [comment]
I will add a tool to convert old saves. keep in mind that the new version is not usable at all right now

**Comment by BobbyTowers** [comment]
Yeah found that out lol

**Comment by diygun** [comment]
Please close issue xD
