### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tolo0** [luca28pet/TimeRanks#9]
Hi. Is it possible to give a player a rank for 24 hours then for the rank to be set back to the rank they had before once the 24 hours is up?

**Comment by Tolo0** [comment]
the plugin doesn't work at all. any chance someone could fix it?

**Comment by luca28pet** [comment]
This plugin is not intended for that kind of use
This is intended for server owners who want players to rank up when they stay online for a given time
Unfortunately it is not possible to do that kind of "temporary" rank you described

Btw, if you want a working version you can find it at github.com/luca28pet/TimeRanks/releases/latest
